default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: task_db
  username: root
  password: root
  host: db

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default