version: '2'
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: task_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
    backend:
        build: backend
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes: 
            - "./backend:/app"
        ports: 
            - "3001:3000"
        depends_on:
            - db
        links:
            - db
        environment:
          DB_USER: root
          DB_NAME: task_db
          DB_PASSWORD: password
          DB_HOST: db
    frontend:
        build: frontend
        command: ionic serve
        volumes: 
            - "./frontend:/app"
        ports: 
            - "8001:8000"
        depends_on:
            - backend
