version: '2'
services:
    db:
        image: mysql:5.7
        restart: always
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: taskdb
        ports:
            - "3307:3306"
    backend:
        build: backend
        image: moustafamahran184/contacts_app_backend:latest
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes: 
            - "./backend:/app"
        ports: 
            - "3000:3000"
        depends_on:
            - db
        links:
            - db
        environment:
          MYSQL_USER: root
          MYSQL_DATABASE: taskdb
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DB_HOST: db
    frontend:
        build: frontend
        image: moustafamahran184/contacts_app_frontend:latest
        stdin_open: true
        command: ionic serve -p 8100 -b '0.0.0.0'
        volumes: 
            - ./frontend:/app
            - node_modules:/app/node_modules
        ports: 
            - "8100:8100"
        depends_on:
            - backend
        environment:
          BE_URL: http://localhost:3000
volumes:
    mysql-data:
    node_modules: